name: SlideShow
author: rpflo
category: Widgets
tags: [slideshow, gallery]
docs: http://moodocs.net/rpflo/mootools-rpflo/SlideShow
demo: http://mootools.net/shell/g3nTM/embedded/result,js,html,css/
current: 0.7