name: SlideShow
author: rpflo
category: Widgets
tags: [slideshow, gallery]
docs: http://moodocs.net/rpflo/mootools-rpflo/SlideShow
demo: http://jsfiddle.net/rpflorence/KkuRZ/embedded/result,html,css,js/
current: 0.7