name: SlideShow
author: rpflo
category: Widgets
tags: [slideshow, gallery, tabs, ticker]
docs: http://moodocs.net/rpflo/mootools-rpflo/SlideShow
demo: http://jsfiddle.net/rpflorence/KaAAK/3/embedded/result,html,css,js/
current: 1.0